import type { IconType } from "react-icons";
import {
  SiJavascript,
  SiTypescript,
  SiPython,
  SiHtml5,
  SiVelocity,
  SiCplusplus,
  SiSwift,
  SiDart,
  SiReact,
  SiNextdotjs,
  SiVuedotjs,
  SiAngular,
  SiFlutter,
  SiGraphql,
  SiBootstrap,
  SiClaude,
  SiCursor,
  SiGithubcopilot,
  SiTailwindcss,
  SiPrimereact,
  SiMui,
  SiSass,
  SiI18Next,
  SiNodedotjs,
  SiSpring,
  SiPrisma,
  SiMongodb,
  SiPostgresql,
  SiMysql,
  SiSupabase,
  SiFirebase,
  SiDocker,
  SiJenkins,
  SiDigitalocean,
  SiGit,
  SiGitlab,
  SiBitbucket,
  SiVagrant,
  SiJfrog,
  SiSentry,
  SiAnthropic,
  SiJest,
  SiTestinglibrary,
  SiCypress,
  SiPwa,
  SiPostman,
  SiSplunk,
  SiGoogletagmanager,
  SiJira,
  SiAsana,
  SiClickup,
  SiNotion,
  SiCss,
  SiRazorpay,
  SiPaypal,
  SiStripe,
  SiGooglegemini,
  SiRedis,
  SiReactrouter,
  SiJsonwebtokens,
  SiMinio,
  SiSocketdotio,
  SiD3,
  SiKeycloak,
  SiAntdesign,
  SiVuetify,
  SiReduxsaga,
  SiTanstack,
  SiWebpack,
  SiModelcontextprotocol,
} from "react-icons/si";
import { FaJava } from "react-icons/fa6";
import {
  TbApi,
  TbBolt,
  TbBooks,
  TbBraces,
  TbBrandAws,
  TbBrandAzure,
  TbBrandCSharp,
  TbBrandOpenai,
  TbClockHour4,
  TbDatabaseSearch,
  TbGauge,
  TbKey,
  TbLayoutDashboard,
  TbPaw,
  TbPlugConnected,
  TbPrompt,
  TbUserShield,
  TbUsersGroup,
  TbWorld,
  TbWorldLatitude,
} from "react-icons/tb";

// Exact-string map from the skill labels in content.ts to a brand icon.
// Compound labels ("Node.js / Express") map to their primary technology.
// A few well-known brands (AWS, Azure, OpenAI, C#) aren't in Simple Icons —
// removed there for trademark-policy reasons — so those borrow a Tabler
// brand icon instead. Anything with no reasonable brand icon (protocols,
// concepts, niche tools) falls back to a generic glyph so every pill still
// gets one.
const SKILL_ICON_MAP: Record<string, IconType> = {
  "JavaScript (ES6)": SiJavascript,
  TypeScript: SiTypescript,
  Python: SiPython,
  HTML5: SiHtml5,
  Java: FaJava,
  Velocity: SiVelocity,
  "C++": SiCplusplus,
  "C#": TbBrandCSharp,
  Swift: SiSwift,
  Dart: SiDart,

  "React (Redux, Hooks)": SiReact,
  "Next.js": SiNextdotjs,
  "Vue.js (Vuex, Pinia)": SiVuedotjs,
  "Redux Saga": SiReduxsaga,
  Zustand: TbPaw, // no brand logo in the icon sets; Zustand's mascot is a bear
  "TanStack Query": SiTanstack,
  "Micro-frontends (Module Federation)": SiWebpack,
  "Ant Design": SiAntdesign,
  Vuetify: SiVuetify,
  AngularJS: SiAngular,
  Flutter: SiFlutter,
  GraphQL: SiGraphql,
  "Tailwind CSS": SiTailwindcss,
  PrimeReact: SiPrimereact,
  "Material UI": SiMui,
  "Sass / Less": SiSass,
  i18next: SiI18Next,

  "Node.js / Express": SiNodedotjs,
  Spring: SiSpring,
  Prisma: SiPrisma,
  MongoDB: SiMongodb,
  PostgreSQL: SiPostgresql,
  MySQL: SiMysql,
  Supabase: SiSupabase,
  "Firebase / Firestore": SiFirebase,
  Redis: SiRedis,
  Keycloak: SiKeycloak,
  "REST APIs": TbApi,
  "WebSocket / Realtime APIs": TbPlugConnected,
  "OAuth 2.0": TbKey,
  RBAC: TbUserShield,
  JWT: SiJsonwebtokens,

  Docker: SiDocker,
  Jenkins: SiJenkins,
  "Azure DevOps Pipelines": TbBrandAzure,
  AWS: TbBrandAws,
  "Digital Ocean": SiDigitalocean,
  Git: SiGit,
  GitLab: SiGitlab,
  Bitbucket: SiBitbucket,
  Vagrant: SiVagrant,
  Artifactory: SiJfrog,
  Sentry: SiSentry,

  "Gemini API": SiGooglegemini,
  "OpenAI API": TbBrandOpenai,
  "Anthropic Claude API": SiAnthropic,
  "pgvector (Postgres)": SiPostgresql,
  "LLM Streaming (SSE)": TbBolt,
  "Prompt / Context Engineering": TbPrompt,
  "RAG (Retrieval-Augmented Generation)": TbDatabaseSearch,
  Claude: SiClaude,
  "GitHub Copilot": SiGithubcopilot,
  Cursor: SiCursor,
  "MCP integrations": SiModelcontextprotocol,

  Jest: SiJest,
  "React Testing Library": SiTestinglibrary,
  Cypress: SiCypress,
  "PWA (Workbox)": SiPwa,
  Postman: SiPostman,
  Splunk: SiSplunk,
  "Google Tag Manager": SiGoogletagmanager,
  Jira: SiJira,
  Asana: SiAsana,
  ClickUp: SiClickup,
  Notion: SiNotion,
  CloudWatch: TbBrandAws,

  "Remote Collaboration": TbWorld,
  "Async Communication": TbClockHour4,
  "Distributed Teams": TbUsersGroup,
  "Cross-Timezone Coordination": TbWorldLatitude,

  // Plain-name aliases — used by experience[].techStack, which names
  // per-role tech as it's actually written in that role's bullets, rather
  // than reusing the aggregate compound labels above (e.g. "React (Redux,
  // Hooks)" implies Redux was used at that specific job, which not every
  // role's bullets support).
  "Vue.js": SiVuedotjs,
  Vuex: SiVuedotjs,
  "Socket.IO (WebSockets)": SiSocketdotio,
  "D3.js": SiD3,
  "Node.js": SiNodedotjs,
  PWA: SiPwa,
  JavaScript: SiJavascript,
  CSS3: SiCss,
  Bootstrap: SiBootstrap,
  Sass: SiSass,
  Razorpay: SiRazorpay,
  PayPal: SiPaypal,
  Stripe: SiStripe,

  // Project tags (projects[].tags). Conceptual tags with no product logo get
  // a matching Tabler icon below; anything unmapped falls back to TbBraces.
  React: SiReact,
  "React Router": SiReactrouter,
  MinIO: SiMinio,
  pgvector: SiPostgresql,
  "Row Level Security": SiPostgresql,
  "Server Actions": SiNextdotjs,
  "Angular-to-React Migration": SiReact,
  "react-admin": TbLayoutDashboard,
  "Context Stuffing": TbBooks,
  "Streaming (SSE)": TbBolt,
  "Rate limiting": TbGauge,
  RAG: TbDatabaseSearch,
};

export function getSkillIcon(skill: string): IconType {
  return SKILL_ICON_MAP[skill] ?? TbBraces;
}
