import type { IconType } from "react-icons";
import {
  SiJavascript,
  SiTypescript,
  SiPython,
  SiHtml5,
  SiVelocity,
  SiCplusplus,
  SiSwift,
  SiDart,
  SiReact,
  SiNextdotjs,
  SiVuedotjs,
  SiAngular,
  SiFlutter,
  SiGraphql,
  SiBootstrap,
  SiClaude,
  SiCursor,
  SiGithubcopilot,
  SiTailwindcss,
  SiPrimereact,
  SiMui,
  SiSass,
  SiI18Next,
  SiNodedotjs,
  SiSpring,
  SiPrisma,
  SiMongodb,
  SiPostgresql,
  SiMysql,
  SiSupabase,
  SiFirebase,
  SiDocker,
  SiJenkins,
  SiDigitalocean,
  SiGit,
  SiGitlab,
  SiBitbucket,
  SiVagrant,
  SiJfrog,
  SiSentry,
  SiAnthropic,
  SiJest,
  SiTestinglibrary,
  SiCypress,
  SiPwa,
  SiPostman,
  SiSplunk,
  SiGoogletagmanager,
  SiJira,
  SiAsana,
  SiClickup,
  SiNotion,
  SiCss,
  SiRazorpay,
  SiPaypal,
  SiStripe,
  SiGooglegemini,
  SiRedis,
  SiReactrouter,
  SiJsonwebtokens,
  SiMinio,
  SiSocketdotio,
  SiD3,
  SiKeycloak,
  SiAntdesign,
  SiVuetify,
  SiReduxsaga,
  SiTanstack,
  SiWebpack,
  SiModelcontextprotocol,
  SiApollographql,
  SiStyledcomponents,
  SiExpress,
  SiEjs,
  SiGooglemaps,
  SiFacebook,
  SiNetlify,
  SiEslint,
  SiPrettier,
  SiGrunt,
  SiGithub,
} from "react-icons/si";
import { FaJava } from "react-icons/fa6";
import {
  TbApi,
  TbBolt,
  TbBooks,
  TbBraces,
  TbCalendarEvent,
  TbClipboardCheck,
  TbCompass,
  TbFileText,
  TbGitPullRequest,
  TbMessages,
  TbRocket,
  TbRuler2,
  TbSchool,
  TbTarget,
  TbUserPlus,
  TbChartDots,
  TbChecks,
  TbClock,
  TbBrandAws,
  TbBrandAzure,
  TbBrandCSharp,
  TbBrandOpenai,
  TbClockHour4,
  TbDatabaseSearch,
  TbGauge,
  TbKey,
  TbLayoutDashboard,
  TbPaw,
  TbPlugConnected,
  TbPrompt,
  TbUserShield,
  TbUsersGroup,
  TbWorld,
  TbWorldLatitude,
} from "react-icons/tb";

// Tabler's C# icon is just the "C#" characters, so beside the "C#" label it
// read as "C# C#". Drawn knocked out of a solid badge instead, so it reads as
// a logo (like the solid C++ hexagon next to it). Takes the same className
// (size) as the other icons; the badge uses the chip's text color.
const CSharpBadge: IconType = ({ className }) => (
  <span
    className={`inline-flex items-center justify-center rounded-[3px] bg-current ${className ?? ""}`}
    aria-hidden="true"
  >
    <TbBrandCSharp style={{ width: "85%", height: "85%", color: "var(--bg-elevated)", strokeWidth: 2.5 }} />
  </span>
);

// Exact-string map from the skill labels in content.ts to a brand icon.
// Compound labels ("Node.js / Express") map to their primary technology.
// A few well-known brands (AWS, Azure, OpenAI, C#) aren't in Simple Icons —
// removed there for trademark-policy reasons — so those borrow a Tabler
// brand icon instead. Anything with no reasonable brand icon (protocols,
// concepts, niche tools) falls back to a generic glyph so every pill still
// gets one.
const SKILL_ICON_MAP: Record<string, IconType> = {
  "JavaScript (ES6)": SiJavascript,
  TypeScript: SiTypescript,
  Python: SiPython,
  HTML5: SiHtml5,
  Java: FaJava,
  Velocity: SiVelocity,
  "C++": SiCplusplus,
  "C#": CSharpBadge,
  Swift: SiSwift,
  Dart: SiDart,

  "React (Redux)": SiReact,
  "Next.js": SiNextdotjs,
  "Vue.js (Vuex, Pinia)": SiVuedotjs,
  "Redux Saga": SiReduxsaga,
  Zustand: TbPaw, // no brand logo in the icon sets; Zustand's mascot is a bear
  "TanStack Query": SiTanstack,
  "Micro-frontends (Module Federation)": SiWebpack,
  "Ant Design": SiAntdesign,
  Vuetify: SiVuetify,
  AngularJS: SiAngular,
  Flutter: SiFlutter,
  GraphQL: SiGraphql,
  "Tailwind CSS": SiTailwindcss,
  PrimeReact: SiPrimereact,
  "Material UI": SiMui,
  "Sass / Less": SiSass,
  i18next: SiI18Next,

  "Node.js / Express": SiNodedotjs,
  Spring: SiSpring,
  Prisma: SiPrisma,
  MongoDB: SiMongodb,
  PostgreSQL: SiPostgresql,
  MySQL: SiMysql,
  Supabase: SiSupabase,
  "Firebase / Firestore": SiFirebase,
  "Firebase (Auth, Firestore, Cloud Messaging)": SiFirebase,
  Redis: SiRedis,
  Keycloak: SiKeycloak,
  "REST APIs": TbApi,
  "WebSocket / Realtime APIs": TbPlugConnected,
  "WebSockets / Realtime APIs (Socket.IO)": TbPlugConnected,
  "OAuth 2.0": TbKey,
  RBAC: TbUserShield,
  JWT: SiJsonwebtokens,

  Docker: SiDocker,
  Jenkins: SiJenkins,
  "Azure DevOps Pipelines": TbBrandAzure,
  AWS: TbBrandAws,
  "Digital Ocean": SiDigitalocean,
  Git: SiGit,
  GitLab: SiGitlab,
  Bitbucket: SiBitbucket,
  Vagrant: SiVagrant,
  Artifactory: SiJfrog,
  Sentry: SiSentry,

  "Gemini API": SiGooglegemini,
  "OpenAI API": TbBrandOpenai,
  "Anthropic Claude API": SiAnthropic,
  "pgvector (Postgres)": SiPostgresql,
  "LLM Streaming (SSE)": TbBolt,
  "Prompt / Context Engineering": TbPrompt,
  "RAG (Retrieval-Augmented Generation)": TbDatabaseSearch,
  Claude: SiClaude,
  "GitHub Copilot": SiGithubcopilot,
  Cursor: SiCursor,
  "MCP integrations": SiModelcontextprotocol,

  Jest: SiJest,
  "React Testing Library": SiTestinglibrary,
  Cypress: SiCypress,
  "PWA (Workbox)": SiPwa,
  Postman: SiPostman,
  Splunk: SiSplunk,
  "Google Tag Manager": SiGoogletagmanager,
  Jira: SiJira,
  Asana: SiAsana,
  ClickUp: SiClickup,
  Notion: SiNotion,
  CloudWatch: TbBrandAws,

  "Remote Collaboration": TbWorld,
  "Async Communication": TbClockHour4,
  "Distributed Teams": TbUsersGroup,
  "Cross-Timezone Coordination": TbWorldLatitude,
  "Fully Remote since 2020": TbWorld,
  "Leading Distributed Teams": TbUsersGroup,
  "Cross-Timezone Collaboration (IST ↔ US/EU)": TbWorldLatitude,

  // Leadership
  "Team Leadership": TbUsersGroup,
  "Hiring & Interviewing": TbUserPlus,
  Mentoring: TbSchool,
  "Performance Reviews": TbClipboardCheck,
  "Sprint Planning": TbCalendarEvent,
  OKRs: TbTarget,
  "Technical Direction": TbCompass,
  "Engineering Standards": TbRuler2,
  "Code Reviews": TbGitPullRequest,
  "Project Ownership & Delivery": TbRocket,
  "Stakeholder Communication": TbMessages,
  "Technical Documentation": TbFileText,

  // Plain-name aliases — used by experience[].techStack, which names
  // per-role tech as it's actually written in that role's bullets, rather
  // than reusing the aggregate compound labels above (e.g. "React (Redux,
  // Hooks)" implies Redux was used at that specific job, which not every
  // role's bullets support).
  "Vue.js": SiVuedotjs,
  Vuex: SiVuedotjs,
  "Socket.IO (WebSockets)": SiSocketdotio,
  "D3.js": SiD3,
  "Node.js": SiNodedotjs,
  PWA: SiPwa,
  JavaScript: SiJavascript,
  CSS3: SiCss,
  Bootstrap: SiBootstrap,
  Sass: SiSass,
  Razorpay: SiRazorpay,
  PayPal: SiPaypal,
  Stripe: SiStripe,

  // Project tags (projects[].tags). Conceptual tags with no product logo get
  // a matching Tabler icon below; anything unmapped falls back to TbBraces.
  React: SiReact,
  "React Router": SiReactrouter,
  MinIO: SiMinio,
  pgvector: SiPostgresql,
  "Row Level Security": SiPostgresql,
  "Server Actions": SiNextdotjs,
  "Angular-to-React Migration": SiReact,

  // Peppo experience (draft entry)
  "Apollo Client": SiApollographql,
  "styled-components": SiStyledcomponents,
  Express: SiExpress,
  EJS: SiEjs,
  "Firebase Cloud Messaging": SiFirebase,
  "Google Maps Platform": SiGooglemaps,
  Heap: TbChartDots, // no Heap logo in the icon sets
  "Facebook Pixel": SiFacebook,
  "AWS ECS / Fargate": TbBrandAws,
  Netlify: SiNetlify,
  ESLint: SiEslint,
  Prettier: SiPrettier,
  Husky: SiGit, // Git hooks — no Husky logo in the icon sets

  // Shippable experience (draft entry)
  "Moment.js": TbClock, // no Moment.js logo in the icon sets
  Grunt: SiGrunt,
  JSHint: TbChecks, // no JSHint logo in the icon sets
  GitHub: SiGithub,
  "react-admin": TbLayoutDashboard,
  "Context Stuffing": TbBooks,
  "Streaming (SSE)": TbBolt,
  "Rate limiting": TbGauge,
  RAG: TbDatabaseSearch,
};

export function getSkillIcon(skill: string): IconType {
  return SKILL_ICON_MAP[skill] ?? TbBraces;
}
